### ISSUE TITLE
Game mode switch causes issues with FM

### ISSUE THREAD

**Issue by ConiNight** [vladikcomper/MegaPCM#2]
https://github.com/user-attachments/assets/1b6f30fa-e66d-4d33-8813-5cc3d767e82e

been having this odd issue where the fm gets messed a bit when changing game modes, this is more noticable with the credits mode
i might suspect its on how i installed megapcm, is there something that interferes with it?
note- the write fm routine is the one used from the tutorial

**Comment by vladikcomper** [comment]
Does it happen consistently? Is it hardware-specific or easy to reproduce in some emulators? (E.g. Blastem, Kega etc)

It's hard to tell without more debugging and testing, but here are my thoughts so far:
- If DAC works fine 99% and it only happens when loading levels (quite a CPU-heavy process), something fishy may be going on with the main sound driver (SMPS).
- Why am I suspicious of SMPS in general and not the MegaPCM and FM write routines? Because even PSGs seem to glitch out (jump sound during one of the transitions);
- Your recording looks like PAL and you seem to optimize SMPS for PAL as well (likely by calling it twice in a row every 5th frame).
- What if there's a data race with it? You execute SMPS twice in a row in VBlank but it takes so long next VBlank arrives (and gets accepted)? This could cause various FM and PSG glitches because of various data races.

I would look into SMPS first, especially if the issue is PAL-specific (or just happens more frequently in PAL). Fixing data race of calling SMPS while previous SMPS instance is running is relatively easy (just create a flag like "SMPS is running", check that it's not set before calling SMPS, set the flag, call SMPS, clear the flag) like so:
```m68k
        tst.b   (SMPS_Running).w        ; is SMPS currently running?
        bne.s   @skip_smps              ; if yes, branch
        move.b  #1,(SMPS_Running).w     ; set "SMPS running flag"
        jsr     SoundDriverUpdate       ; run SMPS
        clr.b   (SMPS_Running).w        ; reset "SMPS running flag"
@skip_smps:
```

**Comment by ConiNight** [comment]
Applied this to the old fix i applied, still has issues...
And to answer a few stuff
1. Happens in emulators, most results provided silent fm voices
2. Also happens on NTSC hardware, so it might not be related to the PAL fix i installed (i do have an unoptimized driver with that issue as well)

**Comment by vladikcomper** [comment]
Can you share the source code by chance? If it's easy to reproduce in many emulators I may have quicker time just tracing this issue.

**Comment by ConiNight** [comment]
i can share the placeholder source code i use for custom smps data (dont mind if some stuff are out of place as its based on a old hack)
edit: i changed the jp level select code to the international code just in case if you access the credits
[used to contain disassembly link]

**Comment by vladikcomper** [comment]
I found the issue, you were spot on that it was related to changing game modes. You basically force-reloaded Mega PCM and its sample table every time game mode was changed (even though SMPS was already running in VBlank in parallel at the time):

```m68k
MainGameLoop:
		jsr	MegaPCM_LoadDriver
		lea	SampleTable,a0
		jsr	MegaPCM_LoadSampleTable

		; <...>

		move.b	(v_gamemode).w,d0 ; load Game Mode
		andi.w	#$1C,d0	; limit Game Mode value to $1C max (change to a maximum of 7C to add more game modes)
		jsr	GameModeArray(pc,d0.w) ; jump to apt location in ROM
		bra.s	MainGameLoop	; loop indefinitely
```

You generally shouldn't do that in the middle of the game, so just move LoadDriver and LoadSampleTable above `MainGameLoop` so it gets executed only once (during init):

```m68k
		jsr	MegaPCM_LoadDriver
		lea	SampleTable,a0
		jsr	MegaPCM_LoadSampleTable

MainGameLoop:
		; <...>

		move.b	(v_gamemode).w,d0 ; load Game Mode
		andi.w	#$1C,d0	; limit Game Mode value to $1C max (change to a maximum of 7C to add more game modes)
		jsr	GameModeArray(pc,d0.w) ; jump to apt location in ROM
		bra.s	MainGameLoop	; loop indefinitely
```

**Comment by ConiNight** [comment]
Now it works properly, thx!
